from __future__ import annotations

"""Generate small Python wrappers for Egg tools from JSON-schema specs."""

import keyword
import re
from typing import Any, Dict, Iterable, List


_IDENT_RE = re.compile(r"^[A-Za-z_]\w*$")


def _safe_ident(name: str) -> bool:
    return bool(_IDENT_RE.match(name or "")) and not keyword.iskeyword(name)


def _ordered_param_names(schema: Dict[str, Any]) -> List[str]:
    params = schema.get("parameters") if isinstance(schema, dict) else None
    if not isinstance(params, dict):
        return []
    props = params.get("properties")
    if not isinstance(props, dict):
        return []
    required = params.get("required")
    req_names = [str(x) for x in required] if isinstance(required, list) else []
    ordered: List[str] = []
    for name in req_names:
        if name in props and _safe_ident(name) and name not in ordered:
            ordered.append(name)
    for name in props.keys():
        if isinstance(name, str) and _safe_ident(name) and name not in ordered:
            ordered.append(name)
    return ordered


def _wrapper_doc(tool_name: str, schema: Dict[str, Any]) -> str:
    desc = str(schema.get("description") or f"Call the Egg tool {tool_name!r}.").strip()
    return desc.replace('"""', r'\"\"\"')


def generate_tool_wrappers_source(tool_schemas: Iterable[Dict[str, Any]]) -> str:
    """Return Python source defining one wrapper per tool schema.

    The generated functions have explicit keyword-friendly signatures derived
    from each tool's JSON-schema properties.  Required fields are positional-or-
    keyword parameters; optional fields default to ``None`` and are omitted from
    the tool payload when left unset.  ``timeout_sec`` is intercepted and
    passed to ``eggtools.tool`` as the bridge/tool-call timeout instead of being
    duplicated in the JSON payload.
    """

    blocks: List[str] = [
        "# Generated by eggthreads.session_runtime.tool_wrappers. Do not edit by hand.",
        "from __future__ import annotations",
        "from typing import Any",
        "",
        "_MISSING = object()",
        "",
    ]
    exported: List[str] = []

    for raw in tool_schemas:
        if not isinstance(raw, dict):
            continue
        fn = raw.get("function") if raw.get("type") == "function" else raw
        if not isinstance(fn, dict):
            continue
        tool_name = str(fn.get("name") or "").strip()
        if not _safe_ident(tool_name):
            continue
        params = fn.get("parameters") if isinstance(fn.get("parameters"), dict) else {}
        required = params.get("required") if isinstance(params, dict) else []
        required_names = [str(x) for x in required] if isinstance(required, list) else []
        ordered = _ordered_param_names(fn)
        required_ordered = [name for name in ordered if name in required_names]
        optional_ordered = [name for name in ordered if name not in required_names]

        signature_parts = [f"{name}: Any" for name in required_ordered]
        if optional_ordered:
            signature_parts.append("*")
            signature_parts.extend(f"{name}: Any = _MISSING" for name in optional_ordered)
        signature_parts.append("**kwargs: Any")
        signature = ", ".join(signature_parts)

        lines: List[str] = [
            f"def {tool_name}({signature}) -> str:",
            f"    \"\"\"{_wrapper_doc(tool_name, fn)}\"\"\"",
            "    args: dict[str, Any] = {}",
        ]
        for name in required_ordered:
            lines.append(f"    args[{name!r}] = {name}")
        for name in optional_ordered:
            lines.append(f"    if {name} is not _MISSING:")
            lines.append(f"        args[{name!r}] = {name}")
        lines.extend([
            "    timeout_sec = args.pop('timeout_sec', None)",
            "    args.update(kwargs)",
            "    if 'timeout_sec' in args:",
            "        timeout_sec = args.pop('timeout_sec')",
            f"    return tool({tool_name!r}, timeout_sec=timeout_sec, **args)",
            "",
        ])
        blocks.append("\n".join(lines))
        exported.append(tool_name)

    blocks.append(f"__all__ = {exported!r}")
    blocks.append("")
    return "\n".join(blocks)
