"""Egg-integrated optimization algorithms."""

from .gepa import (
    CandidateMutation,
    CandidateMutations,
    EggflowGEPAAdapter,
    EggthreadsCandidateProposer,
    EggthreadsReflectionDrive,
    EggthreadsReflectionLM,
    SOLVER_SAFE_PROFILE_NAME,
    SOLVER_SAFE_PROFILE_VERSION,
    SOLVER_SAFE_TOOLS,
    EvaluationSemanticKey,
    ExampleEvaluation,
    GEPAResult,
    ReflectionConversation,
    ReflectionDrive,
    ReflectionEvidence,
    ReflectionOccurrence,
    configure_solver_safe_tools,
    create_solver_safe_study,
    optimize_with_egg,
)

__all__ = [
    "CandidateMutation",
    "CandidateMutations",
    "EggflowGEPAAdapter",
    "EggthreadsCandidateProposer",
    "EggthreadsReflectionDrive",
    "EggthreadsReflectionLM",
    "SOLVER_SAFE_PROFILE_NAME",
    "SOLVER_SAFE_PROFILE_VERSION",
    "SOLVER_SAFE_TOOLS",
    "EvaluationSemanticKey",
    "ExampleEvaluation",
    "GEPAResult",
    "ReflectionConversation",
    "ReflectionDrive",
    "ReflectionEvidence",
    "ReflectionOccurrence",
    "configure_solver_safe_tools",
    "create_solver_safe_study",
    "optimize_with_egg",
]
