#!/usr/bin/env python3
"""Generate frontend CSS selectors from EggW's canonical theme contract."""
from __future__ import annotations

import sys
from pathlib import Path

PACKAGE_ROOT = Path(__file__).resolve().parents[1]
REPO_ROOT = PACKAGE_ROOT.parent
if str(PACKAGE_ROOT) not in sys.path:
    sys.path.insert(0, str(PACKAGE_ROOT))

from eggw.theme_contract import resolve_theme  # noqa: E402
from eggw.theme_registry import DEFAULT_THEME, THEMES  # noqa: E402

OUTPUT = REPO_ROOT / "eggw" / "frontend" / "src" / "app" / "themes.generated.css"
HEADER = """/* Generated by eggw/scripts/generate_theme_css.py. Do not edit by hand. */
/* Source: eggw/eggw/theme-contract.json */
"""


def render() -> str:
    chunks = [HEADER.rstrip()]
    for name in THEMES:
        selector = f':root, [data-theme="{name}"]' if name == DEFAULT_THEME else f'[data-theme="{name}"]'
        values = resolve_theme(name)
        declarations = "\n".join(f"  --{key}: {value};" for key, value in values.items())
        chunks.append(f"{selector} {{\n  color-scheme: {values['theme-polarity']};\n{declarations}\n}}")
    return "\n\n".join(chunks) + "\n"


def main() -> None:
    expected = render()
    if "--check" in sys.argv:
        actual = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if actual != expected:
            raise SystemExit(f"{OUTPUT} is stale; run python ../scripts/generate_theme_css.py")
        return
    OUTPUT.write_text(expected, encoding="utf-8")


if __name__ == "__main__":
    main()
