import type { CSSProperties } from "react";

const token = (color: string, extra: CSSProperties = {}): CSSProperties => ({ color, ...extra });

/** Prism style backed entirely by EggW semantic variables; no dark-only palette. */
export const eggwSyntaxTheme: Record<string, CSSProperties> = {
  'code[class*="language-"]': {
    color: "var(--code-text)",
    background: "var(--code-surface)",
    fontFamily: "var(--font-mono)",
    fontSize: "0.86rem",
    lineHeight: 1.55,
    textShadow: "none",
  },
  'pre[class*="language-"]': {
    color: "var(--code-text)",
    background: "var(--code-surface)",
    fontFamily: "var(--font-mono)",
    fontSize: "0.86rem",
    lineHeight: 1.55,
    textShadow: "none",
    margin: "0.75rem 0",
    padding: "0.75rem 0.9rem",
    overflow: "auto",
  },
  comment: token("var(--syntax-comment)", { fontStyle: "italic" }),
  prolog: token("var(--syntax-comment)"),
  doctype: token("var(--syntax-comment)"),
  cdata: token("var(--syntax-comment)"),
  punctuation: token("var(--code-text)"),
  namespace: token("var(--syntax-variable)"),
  property: token("var(--syntax-variable)"),
  tag: token("var(--syntax-keyword)"),
  constant: token("var(--syntax-number)"),
  symbol: token("var(--syntax-number)"),
  deleted: token("var(--status-danger-text)"),
  boolean: token("var(--syntax-number)"),
  number: token("var(--syntax-number)"),
  selector: token("var(--syntax-string)"),
  "attr-name": token("var(--syntax-variable)"),
  string: token("var(--syntax-string)"),
  char: token("var(--syntax-string)"),
  builtin: token("var(--syntax-function)"),
  inserted: token("var(--status-success-text)"),
  operator: token("var(--syntax-operator)"),
  entity: token("var(--syntax-operator)"),
  url: token("var(--link)"),
  atrule: token("var(--syntax-keyword)"),
  "attr-value": token("var(--syntax-string)"),
  keyword: token("var(--syntax-keyword)", { fontWeight: 650 }),
  function: token("var(--syntax-function)"),
  "class-name": token("var(--syntax-function)"),
  regex: token("var(--syntax-string)"),
  important: token("var(--status-warning-text)", { fontWeight: 650 }),
  variable: token("var(--syntax-variable)"),
  bold: { fontWeight: 700 },
  italic: { fontStyle: "italic" },
};
