from __future__ import annotations

"""Built-in LLM-facing image generation tool."""

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict

from eggllm.image_generation import ImageGenerationConfigError, ImageGenerationError, ImageGenerationProviderError

from ..content_parts import content_to_plain_text
from ..image_generation import (
    generate_openai_image_artifacts,
    image_generation_result_content_parts,
    normalize_image_generation_model_key,
    normalize_openai_image_generation_options,
)
from ..plugins import PluginContext
from ..tools import ToolContext, ToolExecutionResult, ToolRegistry


TOOL_NAME = "generate_image"


def _error(message: str) -> ToolExecutionResult:
    return ToolExecutionResult(f"Error: {message}", reason="error")


def _workspace(ctx: ToolContext) -> Path:
    if ctx.working_dir:
        return Path(ctx.working_dir).resolve()
    db_path = getattr(ctx.db, "path", None)
    if db_path is not None:
        try:
            resolved = Path(db_path).resolve()
            if resolved.parent.name == ".egg":
                return resolved.parent.parent
        except Exception:
            pass
    return Path.cwd().resolve()


def _models_path(ctx: ToolContext, key: str, default: str) -> Any:
    value = ctx.raw.get(key)
    return value if value else default


def _artifact_public_metadata(metadata: Dict[str, Any]) -> dict[str, Any]:
    """Return the concise artifact metadata safe for an LLM-facing result."""

    return {
        key: metadata[key]
        for key in ("artifact_id", "owner_thread_id", "presentation", "mime_type", "filename", "size_bytes", "sha256")
        if key in metadata
    }


def _result_payload(result: Any, content_parts: list[dict[str, Any]]) -> dict[str, Any]:
    return {
        "prompt": result.prompt,
        "model_key": result.model_key,
        "provider_name": result.provider_name,
        "model_name": result.model_name,
        "artifact_count": len(result.artifacts),
        "artifacts": [_artifact_public_metadata(metadata) for metadata in result.metadata],
        "content_parts": content_parts,
        "content_text": content_to_plain_text(content_parts, validate=True),
        "response_metadata": result.response_metadata,
    }


def generate_image_tool(args: Dict[str, Any], ctx: ToolContext) -> ToolExecutionResult:
    """Generate image artifacts through Egg's shared provider-output service."""

    thread_id = str(ctx.thread_id or "").strip()
    if ctx.db is None or not thread_id:
        return _error("generate_image requires a current thread and database context.")

    prompt = str(args.get("prompt") or "").strip()
    if not prompt:
        return _error("image generation prompt is required.")

    try:
        model_key = normalize_image_generation_model_key(args.get("model"), args.get("backend"))
        options = normalize_openai_image_generation_options(args)
    except ValueError as e:
        return _error(str(e))

    try:
        result = generate_openai_image_artifacts(
            _workspace(ctx),
            thread_id,
            prompt,
            model_key=model_key,
            models_path=_models_path(ctx, "models_path", "models.json"),
            all_models_path=_models_path(ctx, "all_models_path", "all-models.json"),
            options=options,
            timeout=ctx.timeout_sec or 600,
        )
    except (ImageGenerationConfigError, ImageGenerationProviderError, ImageGenerationError, ValueError) as e:
        return _error(str(e))

    content_parts = image_generation_result_content_parts(result)
    payload = _result_payload(result, content_parts)
    return ToolExecutionResult(json.dumps(payload, ensure_ascii=False, sort_keys=True), reason="success")


def register_image_generation_tools(registry: ToolRegistry) -> None:
    registry.register(
        name=TOOL_NAME,
        description=(
            "Generate provider-backed image artifacts through Egg's image generation service. "
            "This is an Egg tool, not a provider-native image tool exposed in the normal chat call. "
            "Generated bytes are stored as provider-output artifacts; the tool result contains only "
            "textual JSON metadata and artifact references, never inline bytes or base64."
        ),
        parameters_schema={
            "type": "object",
            "properties": {
                "prompt": {"type": "string", "description": "Required text prompt for image generation."},
                "model": {"type": "string", "description": "Optional image-generation model/backend key."},
                "backend": {"type": "string", "description": "Optional alias for model; must match model when both are provided."},
                "n": {"type": "integer", "description": "Optional number of images to generate, from 1 to 10."},
                "size": {"type": "string", "description": "Optional provider-supported image size, for example 1024x1024."},
                "quality": {"type": "string", "description": "Optional provider-supported image quality."},
                "output_format": {"type": "string", "description": "Optional output format: png, jpeg, or webp."},
                "background": {"type": "string", "description": "Optional provider-supported background setting."},
            },
            "required": ["prompt"],
            "additionalProperties": False,
        },
        impl=generate_image_tool,
        accepts_context=True,
    )


@dataclass(frozen=True)
class ImageGenerationPlugin:
    name: str = "image_generation"
    version: str = "0"

    def register(self, context: PluginContext) -> None:
        if context.tool_registry is not None:
            register_image_generation_tools(context.tool_registry)


__all__ = [
    "ImageGenerationPlugin",
    "TOOL_NAME",
    "generate_image_tool",
    "register_image_generation_tools",
]
