from __future__ import annotations

"""Pure Egg-native output optimizer package."""

from .core import (
    DEFAULT_OPTIMIZER_NAME,
    OptimizeDecision,
    OptimizeRequest,
    OutputFilter,
    OutputOptimizer,
    OutputOptimizerRegistry,
    calculate_size_metadata,
    make_decision,
)
from .config import (
    DEFAULT_OUTPUT_OPTIMIZER_MODE,
    OUTPUT_OPTIMIZER_CONFIG_EVENT_TYPE,
    OUTPUT_OPTIMIZER_ENV,
    OUTPUT_OPTIMIZER_MODE_MIN_CONFIDENCE,
    OUTPUT_OPTIMIZER_MODES,
    OutputOptimizerThreadConfig,
    append_output_optimizer_config_event,
    format_thread_output_optimizer_status,
    get_thread_output_optimizer_config,
    get_thread_output_optimizer_policy_config,
    is_truthy_output_optimizer_flag,
    normalize_output_optimizer_mode,
    output_optimizer_enabled,
    output_optimizer_min_confidence_for_mode,
    set_thread_output_optimizer_enabled,
    set_thread_output_optimizer_mode,
)
from .classify import (
    PathLineContent,
    is_plausible_path_list_line,
    normalize_command_name,
    parse_path_list_lines,
    parse_path_line_content,
    parse_path_line_content_lines,
    request_command_name,
    simple_bash_command_invocation,
    simple_bash_command_name,
    simple_bash_command_words,
)
from .factory import create_default_output_optimizer, default_native_filters
from .observability import (
    format_output_optimizer_summary,
    optimizer_public_metadata_from_output_approval,
)
from .filters.cargo import CargoTestFailureSummaryFilter, is_cargo_test_request, parse_cargo_test_failure_output
from .filters.find import FindPathGroupFilter, is_find_like_request, parse_find_fd_paths
from .filters.git_diff import GitDiffCompactFilter, is_git_diff_request, parse_git_diff
from .filters.git_status import GitStatusCompactFilter, is_git_status_request, parse_git_status_entries, parse_git_status_line
from .filters.grep import GrepRgGroupByFileFilter, is_grep_like_request, parse_grep_rg_matches
from .filters.pytest import PytestFailureSummaryFilter, is_pytest_request, parse_pytest_failure_output
from .filters.python_traceback import PythonTracebackFocusFilter, parse_python_traceback
from .generic import (
    AnsiControlCleanupFilter,
    BoundedHeadTailFilter,
    GenericOutputFilter,
    ProgressNoiseFilter,
    RepeatedLineDedupeFilter,
    bounded_head_tail,
    clean_ansi_controls,
    create_generic_output_optimizer,
    dedupe_repeated_lines,
    default_generic_filters,
    is_obvious_progress_noise_line,
    suppress_progress_noise,
)

__all__ = [
    "DEFAULT_OPTIMIZER_NAME",
    "DEFAULT_OUTPUT_OPTIMIZER_MODE",
    "OUTPUT_OPTIMIZER_CONFIG_EVENT_TYPE",
    "OUTPUT_OPTIMIZER_ENV",
    "OUTPUT_OPTIMIZER_MODE_MIN_CONFIDENCE",
    "OUTPUT_OPTIMIZER_MODES",
    "AnsiControlCleanupFilter",
    "BoundedHeadTailFilter",
    "CargoTestFailureSummaryFilter",
    "FindPathGroupFilter",
    "GenericOutputFilter",
    "GitDiffCompactFilter",
    "GitStatusCompactFilter",
    "GrepRgGroupByFileFilter",
    "OptimizeDecision",
    "OptimizeRequest",
    "OutputOptimizerThreadConfig",
    "OutputFilter",
    "OutputOptimizer",
    "OutputOptimizerRegistry",
    "PathLineContent",
    "ProgressNoiseFilter",
    "PytestFailureSummaryFilter",
    "PythonTracebackFocusFilter",
    "RepeatedLineDedupeFilter",
    "append_output_optimizer_config_event",
    "bounded_head_tail",
    "calculate_size_metadata",
    "clean_ansi_controls",
    "create_default_output_optimizer",
    "create_generic_output_optimizer",
    "dedupe_repeated_lines",
    "default_native_filters",
    "format_thread_output_optimizer_status",
    "format_output_optimizer_summary",
    "get_thread_output_optimizer_config",
    "get_thread_output_optimizer_policy_config",
    "default_generic_filters",
    "is_cargo_test_request",
    "is_find_like_request",
    "is_git_diff_request",
    "is_git_status_request",
    "is_grep_like_request",
    "is_obvious_progress_noise_line",
    "is_plausible_path_list_line",
    "is_pytest_request",
    "is_truthy_output_optimizer_flag",
    "make_decision",
    "normalize_command_name",
    "normalize_output_optimizer_mode",
    "output_optimizer_enabled",
    "output_optimizer_min_confidence_for_mode",
    "optimizer_public_metadata_from_output_approval",
    "parse_cargo_test_failure_output",
    "parse_find_fd_paths",
    "parse_git_diff",
    "parse_git_status_entries",
    "parse_git_status_line",
    "parse_grep_rg_matches",
    "parse_path_list_lines",
    "parse_path_line_content",
    "parse_path_line_content_lines",
    "parse_pytest_failure_output",
    "parse_python_traceback",
    "request_command_name",
    "simple_bash_command_invocation",
    "simple_bash_command_name",
    "simple_bash_command_words",
    "set_thread_output_optimizer_enabled",
    "set_thread_output_optimizer_mode",
    "suppress_progress_noise",
]
