"""eggthreads - Tree-structured conversation threads with event sourcing.

eggthreads provides infrastructure for managing AI conversations as a tree
of threads, where each thread maintains its own message history and can
spawn child threads for parallel exploration or task delegation.

Key features:
- **Thread management**: Create root and child threads, branch conversations
- **Event sourcing**: All state changes recorded as immutable events
- **Tool call workflow**: TC1-TC6 state machine with approval gates
- **Runner actionables**: RA1 (LLM turns), RA2 (tool execution), RA3 (user commands)
- **Sandbox execution**: Isolated command execution with configurable policies

Quick start::

    from eggthreads import ThreadsDB, create_root_thread, append_message

    db = ThreadsDB()
    db.init_schema()

    thread_id = create_root_thread(db, name="My Chat")
    append_message(db, thread_id, role="user", content="Hello!")

See API.md for comprehensive documentation.
"""
from .db import InvocationEventWriter, LeaseLost, ThreadsDB  # type: ignore
from .runner import SubtreeScheduler, ThreadRunner, RunnerConfig, set_default_tool_timeout, get_default_tool_timeout, runner_actionable_resource_class  # type: ignore
from .terminal_safety import sanitize_terminal_text  # type: ignore
from .snapshot import SnapshotBuilder  # type: ignore
from .api import (
    validate_model_handle,
    create_root_thread,
    create_child_thread,
    append_message,
    edit_message,
    delete_message,
    delete_thread,
    is_thread_runnable,
    get_thread_status,
    get_thread_statuses_bulk,
    get_thread_auto_approval_status,
    list_threads,
    list_root_threads,
    get_parent,
    list_children_with_meta,
    list_children_ids,
    current_open_invoke,
    create_snapshot,
    interrupt_thread,
    pause_thread,
    resume_thread,
    set_thread_model,
    current_thread_model,
    current_thread_model_info,
    duplicate_thread,
    duplicate_thread_up_to,
    get_thread_working_directory,
    set_thread_working_directory,
    collect_subtree,
    list_active_threads,
    wait_subtree_idle,
    wait_thread_settled,
    word_count_from_snapshot,
    word_count_from_events,
    set_subtree_working_directory,
    is_descendant_thread,
    send_message_to_child_thread,
    ChildThreadStatus,
    get_child_thread_status,
    get_child_thread_statuses,
    get_active_get_user_message_waiting_note,
    approve_tool_calls_for_thread,
    ToolCallResult,
    ThreadWaitResult,
    enqueue_user_tool_call,
    execute_bash_command,
    execute_bash_command_hidden,
    get_user_command_result,
    wait_for_tool_call_result,
    wait_for_user_command_result,
    wait_for_tool_call_result_async,
    wait_for_user_command_result_async,
    execute_bash_command_async,
    wait_for_threads,
    # Context limit API
    set_context_limit,
    get_context_limit,
    # Continue thread API
    ContinueResult,
    COMPACTION_EVENT_TYPE,
    COMPACTION_CHECKPOINT_SKILL_NAME,
    COMPACTION_CONTEXT_LENGTH_EVENT_TYPE,
    COMPACTION_SUMMARY_REQUEST,
    AUTO_COMPACTION_SUMMARY_REQUEST,
    COMPACTION_SUMMARY_IN_PROGRESS_EVENT_TYPE,
    AutoCompactionResult,
    AutoCompactionThresholdResolution,
    CompactionCommitResult,
    CompactionSummaryRequestResult,
    CompactionStartResolution,
    append_auto_compaction_summary_request,
    append_compaction_summary_request,
    append_compaction_summary_in_progress,
    auto_compact_summary_enabled,
    commit_thread_compaction,
    build_repl_thread_context,
    current_thread_model_context_window_tokens,
    current_effective_compaction_start_event_seq,
    continue_thread,
    filter_messages_for_compaction_provider_context,
    continue_child_thread,
    continue_child_thread_manually,
    continue_thread_manually,
    continue_thread_async,
    find_continue_point,
    latest_thread_compaction,
    latest_effective_thread_compaction,
    latest_effective_thread_compaction_context_length,
    latest_effective_thread_compaction_summary_in_progress,
    has_effective_thread_compaction_summary_in_progress,
    thread_compaction_status,
    list_thread_compaction_context_lengths,
    list_thread_compaction_summary_in_progress_events,
    list_thread_compactions,
    maybe_auto_compact_thread,
    resolve_compaction_start_message,
    resolve_auto_compact_threshold,
    set_thread_compaction_context_length,
    is_thread_continuable,
    # Thread diagnosis
    ThreadDiagnosis,
    diagnose_thread,
    THREAD_RECOVERY_EVENT_TYPE,
    ThreadRecoverySettings,
    get_thread_recovery,
    set_thread_recovery,
    # Thread scheduling API
    UNSET,
    ThreadSchedulingSettings,
    get_thread_scheduling,
    set_thread_scheduling,
)  # type: ignore
from .arg_parser import parse_args, ParsedArgs  # type: ignore
from .tool_state import (
    list_tool_calls_for_thread,
    list_tool_calls_for_message,
    build_tool_call_states,
    thread_state,
    discover_runner_actionable,
)

from .token_count import (
    count_text_tokens,
    llm_message_tps_for_invoke,
    live_llm_tps_for_invoke,
    snapshot_token_stats,
    provider_context_token_stats,
    tool_message_tps_for_call,
    streaming_token_stats,
    total_token_stats,
    thread_token_stats,
)
from .content_parts import (
    ARTIFACT_PART_TYPE,
    ContentPartError,
    attachment_part_from_input_metadata,
    artifact_part_from_provider_output_metadata,
    content_has_artifacts,
    content_has_attachments,
    content_to_plain_text,
    extract_artifact_refs,
    extract_attachment_refs,
    format_attachment_placeholder,
    format_provider_artifact_placeholder,
    normalize_content_to_parts,
    validate_content_part,
    validate_content_parts,
    validate_message_content,
)
from .provider_output_artifacts import (
    PROVIDER_OUTPUT_ARTIFACT_ID_LENGTH,
    PROVIDER_OUTPUT_HASH_ALGORITHM,
    PROVIDER_OUTPUT_METADATA_SCHEMA_VERSION,
    ProviderOutputArtifactAccessError,
    ProviderOutputArtifactError,
    ProviderOutputArtifactNotFoundError,
    SavedProviderOutputArtifact,
    list_provider_output_artifact_metadata,
    provider_output_record_dir,
    provider_output_root_dir,
    provider_output_root_relative_dir,
    promote_provider_output_to_input,
    resolve_provider_output_bytes,
    resolve_provider_output_metadata,
    resolve_provider_output_owner_thread_id,
    save_provider_output_bytes,
    thread_provider_output_dir,
    thread_provider_output_relative_dir,
    validate_provider_output_artifact_id,
)
from .image_generation import (
    GeneratedProviderOutputArtifact,
    ImageGenerationArtifactResult,
    generate_openai_image_artifacts,
    image_generation_result_content_parts,
)
from .tools_config import (
    ToolsConfig,
    ToolPolicyReadError,
    get_thread_tools_config,
    get_tool_statuses_for_config,
    inherit_tools_config_for_child,
    set_thread_tools_enabled,
    disable_tool_for_thread,
    enable_tool_for_thread,
    set_thread_tool_allowlist,
    clear_thread_tool_allowlist,
    set_subtree_tools_enabled,
    disable_tool_for_subtree,
    enable_tool_for_subtree,
    set_thread_allow_raw_tool_output,
)
from .sandbox import (
    wrap_argv_for_sandbox,
    wrap_argv_for_sandbox_with_config,
    wrap_argv_for_sandbox_with_settings,
    SandboxSetupError,
    SandboxProviderRegistry,
    create_sandbox_provider_registry,
    authorize_thread_path_read,
    authorize_thread_path_write,
    sandbox_read_policy_decision,
    sandbox_write_policy_decision,
    get_sandbox_status,
    get_provider_names,
    provider_available,
    set_sandbox_globally_enabled,
    set_sandbox_config,
    get_thread_sandbox_config,
    set_thread_sandbox_config,
    set_subtree_sandbox_config,
    get_thread_sandbox_status,
    enable_user_sandbox_control,
    disable_user_sandbox_control,
    is_user_sandbox_control_enabled,
)

from .session import (
    RuntimeThreadConfig,
    SessionConfig,
    SessionProvider,
    SessionProviderRegistry,
    SessionStatus,
    create_session_provider_registry,
    get_session_provider_names,
    get_thread_session_config,
    get_thread_session_status,
    docker_session_container_name,
    docker_session_db_hash,
    docker_session_available,
    docker_session_mount_dir,
    list_docker_session_containers,
    cleanup_docker_sessions,
    cleanup_thread_sessions,
    get_or_start_docker_session,
    get_or_start_docker_session_handle,
    set_thread_session_config,
    enable_thread_session,
    disable_thread_session,
    stop_thread_session,
    reset_thread_session,
    ensure_thread_session_for_repl,
    append_session_lifecycle_event,
    execute_python_repl,
    execute_bash_repl,
    repl_channel_name,
    runtime_thread_label,
    append_runtime_config,
    find_runtime_thread,
    get_or_create_runtime_thread,
)
from .repl_bridge import (
    EvalContext,
    ReplBridgeError,
    ReplToolTimeout,
    create_eval_context,
    resolve_eval_context,
    dispose_eval_context,
    call_tool as repl_bridge_call_tool,
)
from .approval import (
    ApprovalPolicyRegistry,
    ApprovalRequest,
    ApprovalVerdict,
    aggregate_approval_verdicts,
    create_approval_policy_registry,
    evaluate_approval_policies,
)
from .output_policy import (
    OutputPolicyRegistry,
    OutputPolicyRequest,
    OutputPublicationDecision,
    create_output_policy_registry,
    decide_output_publication,
)
from .output_optimizer.config import (
    DEFAULT_OUTPUT_OPTIMIZER_MODE,
    OUTPUT_OPTIMIZER_CONFIG_EVENT_TYPE,
    OUTPUT_OPTIMIZER_ENV,
    OUTPUT_OPTIMIZER_MODE_MIN_CONFIDENCE,
    OUTPUT_OPTIMIZER_MODES,
    OutputOptimizerThreadConfig,
    append_output_optimizer_config_event,
    format_thread_output_optimizer_status,
    get_thread_output_optimizer_config,
    get_thread_output_optimizer_policy_config,
    normalize_output_optimizer_mode,
    output_optimizer_enabled,
    output_optimizer_min_confidence_for_mode,
    set_thread_output_optimizer_enabled,
    set_thread_output_optimizer_mode,
)
from .command_catalog import (
    CommandContext,
    CommandRegistry,
    CommandResult,
    CommandSpec,
    InputPrefixRegistry,
    InputPrefixSpec,
    SESSION_COMMAND_COMPLETIONS,
    SESSION_ON_COMPLETIONS,
    SESSION_TARGET_COMPLETIONS,
    OUTPUT_OPTIMIZER_COMMAND_COMPLETIONS,
    OUTPUT_OPTIMIZER_MODE_COMPLETIONS,
    EGG_COMMAND_COMPLETIONS,
    EGGW_COMMAND_COMPLETIONS,
    command_completion_names,
    create_default_command_registry,
    create_default_input_prefix_registry,
    render_command_registry_help,
)
from .attachment_staging import (
    build_message_content_with_attachments,
    format_staged_attachments,
    infer_attachment_mime_and_presentation,
    safe_display_filename,
    save_attachment_bytes_for_thread,
    save_local_attachment_for_thread,
)

from .tools import ToolCapabilities, ToolContext, ToolExecutionResult, ToolRegistry, ToolStreamContext, create_default_tools, create_tool_registry
from .skills import Skill, get_skill, list_skills, load_skill_text, render_skill_index, render_skill_tool_output, search_skills

from .llm import create_llm_client

__all__ = [
    'ThreadsDB', 'InvocationEventWriter', 'LeaseLost', 'SubtreeScheduler', 'ThreadRunner', 'RunnerConfig', 'SnapshotBuilder',
    'set_default_tool_timeout', 'get_default_tool_timeout',
    'validate_model_handle', 'create_root_thread', 'create_child_thread', 'append_message', 'edit_message', 'delete_message', 'delete_thread', 'is_thread_runnable', 'get_thread_status', 'get_thread_statuses_bulk', 'get_thread_auto_approval_status',
    'list_threads', 'list_root_threads', 'get_parent', 'list_children_with_meta', 'list_children_ids', 'current_open_invoke',
    'current_thread_model', 'current_thread_model_info', 'duplicate_thread', 'duplicate_thread_up_to',
    'collect_subtree', 'list_active_threads', 'wait_subtree_idle', 'wait_thread_settled',
    'word_count_from_snapshot', 'word_count_from_events',
    'set_subtree_working_directory',
    'is_descendant_thread', 'send_message_to_child_thread',
    'ChildThreadStatus', 'get_child_thread_status', 'get_child_thread_statuses', 'get_active_get_user_message_waiting_note',
    'approve_tool_calls_for_thread',
    'ToolCallResult', 'ThreadWaitResult', 'enqueue_user_tool_call',
    'execute_bash_command', 'execute_bash_command_hidden', 'get_user_command_result', 'wait_for_user_command_result',
    'wait_for_tool_call_result', 'wait_for_tool_call_result_async',
    'wait_for_user_command_result_async',
    'execute_bash_command_async',
    'wait_for_threads',
    # Context limit API
    'set_context_limit', 'get_context_limit',
    # Continue thread API
    'ContinueResult', 'continue_thread', 'continue_child_thread', 'continue_child_thread_manually', 'continue_thread_manually', 'continue_thread_async', 'find_continue_point', 'is_thread_continuable',
    'COMPACTION_EVENT_TYPE', 'COMPACTION_CHECKPOINT_SKILL_NAME', 'COMPACTION_CONTEXT_LENGTH_EVENT_TYPE', 'COMPACTION_SUMMARY_REQUEST', 'AUTO_COMPACTION_SUMMARY_REQUEST', 'COMPACTION_SUMMARY_IN_PROGRESS_EVENT_TYPE', 'AutoCompactionResult', 'AutoCompactionThresholdResolution', 'CompactionCommitResult', 'CompactionSummaryRequestResult', 'CompactionStartResolution',
    'append_auto_compaction_summary_request', 'append_compaction_summary_request', 'append_compaction_summary_in_progress', 'auto_compact_summary_enabled', 'build_repl_thread_context', 'commit_thread_compaction', 'current_thread_model_context_window_tokens', 'current_effective_compaction_start_event_seq',
    'latest_effective_thread_compaction', 'latest_thread_compaction', 'latest_effective_thread_compaction_context_length', 'latest_effective_thread_compaction_summary_in_progress', 'has_effective_thread_compaction_summary_in_progress', 'thread_compaction_status', 'list_thread_compaction_context_lengths', 'list_thread_compaction_summary_in_progress_events', 'list_thread_compactions', 'resolve_compaction_start_message',
    'filter_messages_for_compaction_provider_context', 'maybe_auto_compact_thread', 'resolve_auto_compact_threshold', 'set_thread_compaction_context_length',
    # Thread diagnosis
    'ThreadDiagnosis', 'diagnose_thread', 'sanitize_terminal_text', 'THREAD_RECOVERY_EVENT_TYPE', 'ThreadRecoverySettings', 'get_thread_recovery', 'set_thread_recovery',
    # Thread scheduling API
    'UNSET', 'ThreadSchedulingSettings', 'get_thread_scheduling', 'set_thread_scheduling',
    # Argument parser
    'parse_args', 'ParsedArgs',
    'list_tool_calls_for_thread', 'list_tool_calls_for_message', 'build_tool_call_states', 'thread_state',
    'discover_runner_actionable', 'runner_actionable_resource_class',
    'ToolsConfig', 'ToolPolicyReadError', 'get_thread_tools_config', 'get_tool_statuses_for_config', 'inherit_tools_config_for_child', 'set_thread_tools_enabled', 'disable_tool_for_thread', 'enable_tool_for_thread',
    'set_thread_tool_allowlist', 'clear_thread_tool_allowlist',
    'set_subtree_tools_enabled', 'disable_tool_for_subtree', 'enable_tool_for_subtree',
    'set_thread_allow_raw_tool_output',
    'SandboxSetupError', 'SandboxProviderRegistry', 'create_sandbox_provider_registry',
    'authorize_thread_path_read', 'authorize_thread_path_write',
    'sandbox_read_policy_decision', 'sandbox_write_policy_decision',
    'get_provider_names', 'provider_available',
    'wrap_argv_for_sandbox', 'wrap_argv_for_sandbox_with_config',
    'wrap_argv_for_sandbox_with_settings', 'get_sandbox_status',
    'set_sandbox_globally_enabled', 'set_sandbox_config',
    'get_thread_sandbox_config', 'set_thread_sandbox_config', 'set_subtree_sandbox_config', 'get_thread_sandbox_status',
    'ToolCapabilities', 'ToolContext', 'ToolExecutionResult', 'ToolRegistry', 'ToolStreamContext', 'create_default_tools', 'create_tool_registry',
    'Skill', 'get_skill', 'list_skills', 'load_skill_text', 'render_skill_index', 'render_skill_tool_output', 'search_skills',
    'create_llm_client',
    'count_text_tokens', 'llm_message_tps_for_invoke', 'live_llm_tps_for_invoke', 'tool_message_tps_for_call', 'snapshot_token_stats', 'provider_context_token_stats', 'streaming_token_stats', 'total_token_stats', 'thread_token_stats', 'EventWatcher',
    'enable_user_sandbox_control',
    'disable_user_sandbox_control',
    'is_user_sandbox_control_enabled',
    'RuntimeThreadConfig', 'SessionConfig', 'SessionProvider', 'SessionProviderRegistry', 'SessionStatus',
    'create_session_provider_registry', 'get_session_provider_names',
    'get_thread_session_config', 'get_thread_session_status',
    'docker_session_container_name', 'docker_session_db_hash', 'docker_session_available',
    'docker_session_mount_dir', 'list_docker_session_containers', 'cleanup_docker_sessions',
    'cleanup_thread_sessions',
    'get_or_start_docker_session',
    'get_or_start_docker_session_handle',
    'set_thread_session_config',
    'enable_thread_session', 'disable_thread_session', 'stop_thread_session', 'reset_thread_session', 'ensure_thread_session_for_repl',
    'append_session_lifecycle_event',
    'execute_python_repl', 'execute_bash_repl', 'repl_channel_name',
    'runtime_thread_label', 'append_runtime_config',
    'find_runtime_thread', 'get_or_create_runtime_thread',
    'EvalContext', 'ReplBridgeError', 'ReplToolTimeout',
    'create_eval_context', 'resolve_eval_context', 'dispose_eval_context',
    'repl_bridge_call_tool',
    'CommandContext', 'CommandRegistry', 'CommandResult', 'CommandSpec',
    'attachment_part_from_input_metadata',
    'ApprovalPolicyRegistry', 'ApprovalRequest', 'ApprovalVerdict',
    'aggregate_approval_verdicts', 'create_approval_policy_registry', 'evaluate_approval_policies',
    'OutputPolicyRegistry', 'OutputPolicyRequest', 'OutputPublicationDecision',
    'create_output_policy_registry', 'decide_output_publication',
    'DEFAULT_OUTPUT_OPTIMIZER_MODE', 'OUTPUT_OPTIMIZER_CONFIG_EVENT_TYPE', 'OUTPUT_OPTIMIZER_ENV',
    'OUTPUT_OPTIMIZER_MODE_MIN_CONFIDENCE', 'OUTPUT_OPTIMIZER_MODES', 'OutputOptimizerThreadConfig',
    'append_output_optimizer_config_event', 'format_thread_output_optimizer_status',
    'get_thread_output_optimizer_config', 'get_thread_output_optimizer_policy_config',
    'normalize_output_optimizer_mode', 'output_optimizer_enabled', 'output_optimizer_min_confidence_for_mode',
    'set_thread_output_optimizer_enabled', 'set_thread_output_optimizer_mode',
    'InputPrefixRegistry', 'InputPrefixSpec',
    'SESSION_COMMAND_COMPLETIONS', 'SESSION_ON_COMPLETIONS', 'SESSION_TARGET_COMPLETIONS',
    'OUTPUT_OPTIMIZER_COMMAND_COMPLETIONS', 'OUTPUT_OPTIMIZER_MODE_COMPLETIONS',
    'EGG_COMMAND_COMPLETIONS', 'EGGW_COMMAND_COMPLETIONS',
    'command_completion_names', 'create_default_command_registry', 'create_default_input_prefix_registry',
    'render_command_registry_help',
    'build_message_content_with_attachments', 'format_staged_attachments',
    'infer_attachment_mime_and_presentation', 'safe_display_filename',
    'save_attachment_bytes_for_thread', 'save_local_attachment_for_thread',
    'list_provider_output_artifact_metadata',
    'GeneratedProviderOutputArtifact', 'ImageGenerationArtifactResult',
    'generate_openai_image_artifacts', 'image_generation_result_content_parts',
]
from .event_watcher import EventWatcher
